---
- name: Docker Compose Master UP
  hosts: master
  gather_facts: no
  remote_user: root

  tasks:
    - name: chmod dashboards 
      become: yes
      shell: chmod 777 -R /docker-compose/dashboards

    - name: Run Grafana
      become: yes
      shell: docker-compose -f /docker-compose/grafana-node-prom.yaml up -d
